// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZcb5KYJthkfxe-i0hlgiVfFxB3j1Jctw',
    appId: '1:643467714418:android:8c192b5dd1a551519007eb',
    messagingSenderId: '643467714418',
    projectId: 'jphacks2022',
    storageBucket: 'jphacks2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6BQx1tjp3p9jED0ZP-qlYX9x2ISDtMgc',
    appId: '1:643467714418:ios:e503544a3fb1e0159007eb',
    messagingSenderId: '643467714418',
    projectId: 'jphacks2022',
    storageBucket: 'jphacks2022.appspot.com',
    androidClientId: '643467714418-c0bh1muhrasd4r19ev2nm3ns4ssilo1m.apps.googleusercontent.com',
    iosClientId: '643467714418-j30veforotsj4t16js3vmgh7h77kndpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
